name: cedar
channels:
  - conda-forge
  - https://conda.software.inl.gov/public
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - contourpy=1.3.3=py313h7037e92_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - endf=0.1.9=py313h7033f15_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fltk=1.3.10=hff38c0f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py313h3dea7bd_0
  - freeglut=3.2.2=ha6d2627_3
  - freeimage=3.18.0=h49ef1fa_24
  - freetype=2.14.1=ha770c72_0
  - future=1.0.0=pyhd8ed1ab_2
  - gmp=6.3.0=hac33072_2
  - hdf5=1.14.3=nompi_h2d575fe_109
  - icu=75.1=he02047a_0
  - imath=3.2.2=hde8ca8f_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.8=he3c4edf_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_2
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopengl=1.7.0=ha4b6fd6_2
  - libpng=1.6.50=h421ea60_1
  - libraw=0.21.4=h9969a89_0
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=6.0.2=py313h4a16004_2
  - matplotlib-base=3.10.7=py313h683a580_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncrystal=4.2.10=pyhf5fbd30_1
  - ncrystal-core=4.2.10=pyh8af1aa0_1
  - ncrystal-lib=4.2.10=h7033f15_1
  - ncrystal-python=4.2.10=pyh8af1aa0_1
  - ncurses=6.5=h2d0b736_3
  - njoy2016=2016.78=py313he9baced_1
  - numpy=2.3.4=py313hf6604e3_0
  - occt=7.8.1=novtk_he2768ca_103
  - openexr=3.4.3=he10986b_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.25.3=h8d634f6_0
  - openmc=0.15.2=nodagmc_nompi_py313he95176b_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py313h50355cd_0
  - pixman=0.46.4=h54a6638_1
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.13.9=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - rapidjson=1.1.0.post20240409=h3f2d84a_2
  - readline=8.2=h8c095d6_2
  - scipy=1.16.3=py313h11c21cd_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxmu=1.2.1=hb9d3cd8_1
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alabaster==1.0.0
      - babel==2.17.0
      - cedar==0.1.0
      - certifi==2025.11.12
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - coolprop==7.2.0
      - docutils==0.21.2
      - gmsh==4.15.0
      - h5py==3.15.1
      - idna==3.11
      - imagesize==1.4.1
      - jinja2==3.1.6
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - meshio==5.3.5
      - netcdf4==1.7.3
      - pip==25.3
      - requests==2.32.5
      - rich==14.2.0
      - roman-numerals==4.1.0
      - roman-numerals-py==4.1.0
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - urllib3==2.6.2
      - wheel==0.45.1
prefix: /home/stonehill/miniforge/envs/cedar
